<?php /** @var Oggetto_GeoDetection_Block_Shipping_Calculator $this */ ?>
<?php if ($this->isEnabled()):
    $calculations = $this->calculateShipping(); ?>

    <?php if ($calculations): ?>
        <div class="shipping-calculations">
            <h3 id="shipping-calculations-title">
                <span class="shipping-calculations-title_span not-selectable">
                    <?php echo $this->__('Shipping prices'); ?>
                </span>
            </h3>
            <ul class="shipping-calculations-list">
                <?php foreach($calculations as $carrier => $methods): ?>
                    <li class="shipping-calculations-list_li">
                        <h4 class="shipping-calculations-list-carrier"><?php echo $carrier; ?></h4>

                        <ul class="shipping-calculations-list_li_ul">
                            <?php foreach($methods as $title => $method): ?>
                                <li>
                                    <span class="shipping-calculations-list-method">
                                        <?php echo $title ?>
                                    </span>
                                    <span class="shipping-calculations-list-calculation">
                                        <?php echo Mage::helper('core')->formatPrice($method['price']); ?>
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

<?php endif; ?>
