<?php /** @var Oggetto_GeoDetection_Block_Shipping_Calculator $this */ ?>
<?php if ($this->isEnabled()):
    $calculations = $this->calculateShipping(); ?>

    <?php if ($calculations): ?>
        <ul>
            <?php foreach($calculations as $carrier => $methods): ?>
                <li>
                    <h2 style="margin-bottom:1px;"><?php echo $carrier; ?></h2>

                    <?php foreach($methods as $title => $method): ?>
                        <h3><?php echo $title . ' ' . Mage::helper('core')->formatPrice($method['price']); ?></h3>
                    <?php endforeach; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>
