<?php /** @var Oggetto_GeoDetection_Block_Shipping_Calculator $this */ ?>
<?php if ($this->isEnabled()):
    $calculations = $this->getDeliveryPriceAndTime(); ?>

    <?php if ($calculations): ?>
        <ul>
            <?php foreach($calculations as $carrier => $methods): ?>
                <li style="margin-bottom:5px;">
                    <h6 style="margin-bottom:0;"><?php echo $carrier; ?></h6>

                    <?php foreach($methods as $title => $method): ?>
                        <span>
                            <?php echo $title . ' ' . Mage::helper('core')->formatPrice($method['price']); ?>
                        </span>
                    <?php endforeach; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>
